# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Can be either a string :
requestInfoReplyComment: >
  Apreciamos que nos brindes mas informacion acerca de este issue/pr!
